<?php

/**
 * Coffee Time example configuration. Copy this file to `config.php` and edit
 * it. The application reloads it on every request.
 */
return [
    // Price of one coffee in cents.
    'priceCents' => 150,

    // Invite code required during registration.
    'invite' => 'BEANS-2026',

    // User IDs (as strings) with administrator privileges.
    'admins' => [],

    // WebAuthn relying-party ID (host only, without scheme or port).
    'rpId' => 'localhost',

    // Complete origin, including scheme and port.
    'origin' => 'http://localhost:8123',

    // SQLite path. Keep it outside public/.
    'dbPath' => __DIR__ . '/data/coffee.sqlite',

    // Test endpoints (/api/test/*). Always false in production.
    'testMode' => false,
    'testToken' => '',

    // RSA public key generated by: php tools/decrypt-users.php --genkey
    // Never put the corresponding private key on the server.
    'adminPublicKey' => <<<'PEM'
-----BEGIN PUBLIC KEY-----
REPLACE_WITH_YOUR_PUBLIC_KEY
-----END PUBLIC KEY-----
PEM,

    // Secret used to detect duplicate names without storing plaintext.
    'namePepper' => 'change-me-to-a-long-random-value',
];
