<?php

/**
 * Coffee Time example configuration. Copy this file to `config.php` and edit
 * it. The application reloads it on every request.
 *
 * Manually editing this file is optional: a fresh deployment with no
 * adminPublicKey and no users offers the in-app setup wizard instead, which
 * generates the admin keypair in the browser (the private key is only
 * offered for download, never uploaded) and stores adminPublicKey,
 * priceCents, and invite itself. This file remains the supported path for
 * scripted or production deployments that want everything fixed ahead of
 * time.
 */
return [
    // Price of one coffee in cents. Once an admin changes the price from the
    // in-app settings screen (or the setup wizard has run), the stored value
    // overrides this one — see 'invite' below and the README's "Settings
    // precedence" section.
    'priceCents' => 150,

    // Invite code required during registration. Like priceCents, an in-app
    // change (setup wizard or admin settings) overrides this file's value on
    // every later request; edit this only to set the initial/fallback value.
    'invite' => 'BEANS-2026',

    // User IDs (as strings) with administrator privileges.
    'admins' => [],

    // WebAuthn relying-party ID (host only, without scheme or port).
    'rpId' => 'localhost',

    // Complete origin, including scheme and port.
    'origin' => 'http://localhost:8123',

    // SQLite path. Keep it outside public/. Ignored when 'db' below selects
    // the mysql driver.
    'dbPath' => __DIR__ . '/data/coffee.sqlite',

    // Optional: use MySQL/MariaDB instead of SQLite. Uncomment and fill in
    // your own values; an invalid or incomplete block falls back to SQLite.
    // 'db' => [
    //     'driver' => 'mysql',
    //     'host' => '127.0.0.1',
    //     'port' => 3306,
    //     'database' => 'coffee',
    //     'user' => 'coffee',
    //     'password' => 'change-me',
    //     'charset' => 'utf8mb4',
    // ],

    // Test endpoints (/api/test/*). Always false in production.
    'testMode' => false,
    'testToken' => '',

    // RSA public key generated by: php tools/decrypt-users.php --genkey
    // Never put the corresponding private key on the server. Leave this
    // empty to use the in-app setup wizard instead: it generates the keypair
    // in the browser and stores the public half via the settings table
    // (once set that way, it takes precedence over this file — see the
    // "Settings precedence" section in README.md). Unlike priceCents/invite,
    // it cannot be changed again from the app afterward: doing so would
    // strand every name already encrypted with the old key.
    'adminPublicKey' => <<<'PEM'
-----BEGIN PUBLIC KEY-----
REPLACE_WITH_YOUR_PUBLIC_KEY
-----END PUBLIC KEY-----
PEM,

    // Secret used to detect duplicate names without storing plaintext. If
    // left unset here, the setup wizard generates a random one and stores it
    // via the settings table on first run; like adminPublicKey, it is never
    // rewritten afterward, since that would invalidate every existing
    // duplicate-name check.
    'namePepper' => 'change-me-to-a-long-random-value',
];
