<?php

declare(strict_types=1);

namespace Coffee;

use PDO;

/**
 * One-time codes for linking a second device to an existing account:
 * self-generated ("self", e.g. for a second device of one's own) or
 * generated by an admin ("admin", after device loss). At most one unused
 * code exists per account at any time; a newly generated code immediately
 * invalidates any prior one.
 *
 * As with Ceremonies, the plaintext code is never stored, only its SHA-256
 * hash. The code is shown to the user exactly once.
 */
final class LinkCodes
{
    /** Unambiguous alphabet: no I/O/0/1, to avoid confusion. */
    private const ALPHABET = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';

    /** Code length excluding the separator dash. */
    private const CODE_LENGTH = 8;

    /** Validity period of a self-generated code: 15 minutes. */
    public const SELF_TTL = 900;

    /** Validity period of an admin-generated code: 1 hour. */
    public const ADMIN_TTL = 3600;

    /**
     * Generates a new code for the user. Any existing, unused code
     * belonging to the same user is deleted in the process — there is
     * always at most one active code per account.
     *
     * @return array{code: string, expiresAt: int}
     */
    public static function create(string $userId, string $createdBy, int $ttlSeconds): array
    {
        $raw = self::randomCode();
        $hash = hash('sha256', $raw);
        $now = Clock::now();
        $expiresAt = $now + $ttlSeconds;

        Db::transaction(static function (PDO $pdo) use ($userId, $hash, $createdBy, $expiresAt, $now): void {
            // Only one active code per account: a new code invalidates any
            // still-unused predecessor.
            $pdo->prepare('DELETE FROM link_codes WHERE user_id = ? AND used = 0')
                ->execute([(int) $userId]);

            $statement = $pdo->prepare(
                'INSERT INTO link_codes (user_id, code_hash, created_by, used, expires_at, created_at)
                 VALUES (?, ?, ?, 0, ?, ?)'
            );
            $statement->execute([(int) $userId, $hash, $createdBy, $expiresAt, $now]);
        });

        return ['code' => self::format($raw), 'expiresAt' => $expiresAt];
    }

    /**
     * Normalizes a user input: uppercased, everything outside the alphabet
     * stripped (so dashes, lowercase, and spaces don't matter). Returns ''
     * if exactly CODE_LENGTH characters don't remain afterward.
     */
    public static function normalize(string $code): string
    {
        $upper = strtoupper($code);
        $filtered = preg_replace('/[^' . preg_quote(self::ALPHABET, '/') . ']/', '', $upper) ?? '';

        return strlen($filtered) === self::CODE_LENGTH ? $filtered : '';
    }

    /**
     * Returns the row for a valid (unused, not expired) code without
     * consuming it.
     *
     * @return array<string, mixed>|null
     */
    public static function peek(string $code): ?array
    {
        $normalized = self::normalize($code);
        if ($normalized === '') {
            return null;
        }

        $row = Db::fetchRow(
            'SELECT * FROM link_codes WHERE code_hash = ? AND used = 0',
            [hash('sha256', $normalized)]
        );
        if ($row === null || self::isExpired($row)) {
            return null;
        }

        return $row;
    }

    /**
     * Consumes the code atomically — a second call with the same code
     * returns null. Guarded UPDATE ... WHERE used = 0 with a rowCount
     * check, mirroring Ceremonies::consume().
     *
     * @return array<string, mixed>|null
     */
    public static function consume(string $code): ?array
    {
        $normalized = self::normalize($code);
        if ($normalized === '') {
            return null;
        }
        $hash = hash('sha256', $normalized);

        return Db::transaction(static function (PDO $pdo) use ($hash): ?array {
            $row = Db::fetchRow('SELECT * FROM link_codes WHERE code_hash = ? AND used = 0', [$hash], $pdo);
            if ($row === null || self::isExpired($row)) {
                return null;
            }

            $update = $pdo->prepare('UPDATE link_codes SET used = 1 WHERE id = ? AND used = 0');
            $update->execute([$row['id']]);
            if ($update->rowCount() !== 1) {
                // A concurrent request won the race.
                return null;
            }

            return $row;
        });
    }

    /** @param array<string, mixed> $row */
    private static function isExpired(array $row): bool
    {
        $expiresAt = isset($row['expires_at']) && is_numeric($row['expires_at']) ? (int) $row['expires_at'] : 0;

        return $expiresAt < Clock::now();
    }

    private static function randomCode(): string
    {
        $chars = '';
        $max = strlen(self::ALPHABET) - 1;
        for ($i = 0; $i < self::CODE_LENGTH; $i++) {
            $chars .= self::ALPHABET[random_int(0, $max)];
        }

        return $chars;
    }

    /** 'ABCDEFGH' -> 'ABCD-EFGH', for display to the user. */
    private static function format(string $raw): string
    {
        return substr($raw, 0, 4) . '-' . substr($raw, 4);
    }
}
